<#
.SYNOPSIS
    Generate .github/CODEOWNERS from gald3r subsystem specs (T1299).

.DESCRIPTION
    Reads every .gald3r/subsystems/**/*.md spec, parses the YAML frontmatter
    `owners:` and `locations.code:` lists, and emits one CODEOWNERS line per
    code path for each subsystem that declares non-empty owners.

    Idempotent and safe to re-run. The generated (auto) block is rewritten each
    run; anything the user adds below the `# CUSTOM ENTRIES BELOW` marker is
    preserved verbatim.

    No-op (exit 0, message) when no subsystem declares owners.

.PARAMETER ProjectRoot
    Repo root containing .gald3r/. Defaults to walking up from the script.

.PARAMETER DryRun
    Print the would-be CODEOWNERS to stdout without writing the file.

.EXAMPLE
    pwsh -File codeowners_gen.ps1 -DryRun
    pwsh -File codeowners_gen.ps1
#>
[CmdletBinding()]
param(
    [string]$ProjectRoot,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$CUSTOM_MARKER = '# CUSTOM ENTRIES BELOW'

function Find-ProjectRoot {
    param([string]$Start)
    $dir = if ($Start) { $Start } else { $PSScriptRoot }
    for ($i = 0; $i -lt 12 -and $dir; $i++) {
        if (Test-Path (Join-Path $dir '.gald3r')) { return $dir }
        $parent = Split-Path $dir -Parent
        if ($parent -eq $dir) { break }
        $dir = $parent
    }
    return (Get-Location).Path
}

# Minimal frontmatter reader: returns owners[] and code-location paths[] for a spec.
function Read-SpecOwners {
    param([string]$Path)
    $lines = Get-Content -LiteralPath $Path -ErrorAction SilentlyContinue
    if (-not $lines) { return $null }
    # frontmatter is between the first two '---' fences
    $fence = @(); for ($i = 0; $i -lt $lines.Count; $i++) { if ($lines[$i].Trim() -eq '---') { $fence += $i; if ($fence.Count -eq 2) { break } } }
    if ($fence.Count -lt 2) { return $null }
    $fm = $lines[($fence[0] + 1)..($fence[1] - 1)]

    $owners = @()
    $codePaths = @()
    $inLocations = $false
    foreach ($l in $fm) {
        # owners: [a, "@b/c"]   (inline list form)
        if ($l -match '^\s*owners\s*:\s*\[(.*)\]\s*$') {
            $owners = ($matches[1] -split ',') | ForEach-Object { $_.Trim().Trim('"').Trim("'") } | Where-Object { $_ }
            continue
        }
        if ($l -match '^\s*locations\s*:\s*$') { $inLocations = $true; continue }
        if ($inLocations) {
            # leave locations block when a non-indented key appears
            if ($l -match '^\S') { $inLocations = $false }
            elseif ($l -match '^\s+code\s*:\s*\[(.*)\]\s*$') {
                $codePaths = ($matches[1] -split ',') | ForEach-Object { $_.Trim().Trim('"').Trim("'") } | Where-Object { $_ }
            }
        }
    }
    if (-not $owners -or $owners.Count -eq 0) { return $null }
    return [pscustomobject]@{ Owners = $owners; CodePaths = $codePaths; Spec = (Split-Path $Path -Leaf) }
}

$root = Find-ProjectRoot -Start $ProjectRoot
$subsysDir = Join-Path $root '.gald3r/subsystems'
if (-not (Test-Path $subsysDir)) {
    Write-Host "No .gald3r/subsystems/ directory found at $root. Nothing to do."
    exit 0
}

$specs = Get-ChildItem -Path $subsysDir -Recurse -Filter '*.md' -File |
    Where-Object { $_.Name -notmatch '^SUBSYSTEM' }   # skip index/graph artifacts

$entries = @()
foreach ($s in $specs) {
    $info = Read-SpecOwners -Path $s.FullName
    if (-not $info) { continue }
    $ownerStr = ($info.Owners | ForEach-Object { if ($_ -match '^@') { $_ } else { "@$_" } }) -join ' '
    $paths = if ($info.CodePaths.Count -gt 0) { $info.CodePaths } else { @() }
    foreach ($p in $paths) {
        # normalize to a leading-slash repo path pattern
        $pat = '/' + ($p -replace '^[./]+', '') -replace '\\', '/'
        $entries += [pscustomobject]@{ Pattern = $pat; Owners = $ownerStr; Spec = $info.Spec }
    }
}

if ($entries.Count -eq 0) {
    Write-Host "No subsystem declares a non-empty owners: list. CODEOWNERS not generated (no-op)."
    exit 0
}

$nl = "`n"
$auto = @()
$auto += '# Auto-generated by g-codeowners-gen — do not hand-edit above the marker.'
$auto += "# Source: .gald3r/subsystems/*.md frontmatter (owners: + locations.code:)."
$auto += "# Regenerate: @g-codeowners-gen  (helper: codeowners_gen.ps1)"
$auto += ''
foreach ($e in ($entries | Sort-Object Pattern)) {
    $auto += ('{0} {1}' -f $e.Pattern, $e.Owners)
}
$auto += ''
$auto += $CUSTOM_MARKER
$autoBlock = ($auto -join $nl)

$codeownersPath = Join-Path $root '.github/CODEOWNERS'

# Preserve any existing custom entries below the marker.
$customBlock = ''
if (Test-Path $codeownersPath) {
    $existing = Get-Content -LiteralPath $codeownersPath -Raw
    $idx = $existing.IndexOf($CUSTOM_MARKER)
    if ($idx -ge 0) {
        $after = $existing.Substring($idx + $CUSTOM_MARKER.Length)
        $customBlock = $after.TrimStart("`r", "`n")
    }
}

$final = $autoBlock
if ($customBlock) { $final += $nl + $customBlock.TrimEnd() + $nl } else { $final += $nl }

if ($DryRun) {
    Write-Host "--- DRY RUN: .github/CODEOWNERS ($($entries.Count) entries from $((($entries.Spec) | Sort-Object -Unique).Count) subsystem(s)) ---"
    Write-Output $final
    exit 0
}

$ghDir = Join-Path $root '.github'
if (-not (Test-Path $ghDir)) { New-Item -ItemType Directory -Path $ghDir -Force | Out-Null }
# UTF-8 without BOM (avoid the BUG-016/041 mojibake class)
[System.IO.File]::WriteAllText($codeownersPath, $final, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $codeownersPath ($($entries.Count) ownership line(s)); custom entries preserved."
