<#
.SYNOPSIS
    Generates SKILL_INDEX.md across all 5 IDE skill folders from canonical .cursor/skills/g-skl-*/SKILL.md frontmatter.

.DESCRIPTION
    Part of Task 873 (Skill Chaining). The SKILL_INDEX.md file is a one-line-per-skill
    catalogue that lets agents discover skills without loading their full bodies. The
    canonical source is .cursor/skills/g-skl-*/SKILL.md frontmatter (`name:` + `description:`).

    The script:
      1. Walks .cursor/skills/g-skl-* for SKILL.md files
      2. Parses frontmatter `name:` and `description:` (handles plain and folded `>-` forms)
      3. Emits SKILL_INDEX.md to .cursor/, .claude/, .agent/, .codex/, .opencode/ skill folders
      4. Is idempotent — re-running on unchanged input yields unchanged output

    .copilot/ has commands only (no skills folder) and is excluded by design — this is a
    documented Phase 1 platform constraint, not an oversight.

.PARAMETER Apply
    Write the SKILL_INDEX.md files. Without this flag the script reports what would change.

.PARAMETER RepoRoot
    Override the repo root. Defaults to the parent directory of this script.

.EXAMPLE
    .\scripts\generate_skill_index.ps1
    # Dry-run: show what would change

.EXAMPLE
    .\scripts\generate_skill_index.ps1 -Apply
    # Actually write SKILL_INDEX.md to all 5 IDE skill folders
#>

param(
    [switch]$Apply,
    [string]$RepoRoot
)

$ErrorActionPreference = 'Stop'

if (-not $RepoRoot) {
    $RepoRoot = Split-Path -Parent $PSScriptRoot
}

if (-not (Test-Path (Join-Path $RepoRoot '.cursor/skills'))) {
    Write-Error "Could not locate .cursor/skills under '$RepoRoot'."
    exit 2
}

$canonicalSkillsDir = Join-Path $RepoRoot '.cursor/skills'
$targets = @(
    (Join-Path $RepoRoot '.cursor/skills'),
    (Join-Path $RepoRoot '.claude/skills'),
    (Join-Path $RepoRoot '.agent/skills'),
    (Join-Path $RepoRoot '.codex/skills'),
    (Join-Path $RepoRoot '.opencode/skills')
)

function Get-SkillFrontmatter {
    param([string]$Path)

    # Read as UTF-8 explicitly so em-dashes and other non-ASCII characters
    # in description fields round-trip correctly.
    $raw = [System.IO.File]::ReadAllText($Path, [System.Text.UTF8Encoding]::new($false))
    $lines = $raw -split "`r?`n"
    if ($lines.Count -lt 3 -or $lines[0].Trim() -ne '---') {
        return $null
    }

    # Find closing '---'
    $endIdx = -1
    for ($i = 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i].Trim() -eq '---') { $endIdx = $i; break }
    }
    if ($endIdx -lt 0) { return $null }

    $fmLines = $lines[1..($endIdx - 1)]

    $name = $null
    $description = $null
    $i = 0
    while ($i -lt $fmLines.Count) {
        $line = $fmLines[$i]

        if ($line -match '^\s*name\s*:\s*(.+)$') {
            $name = $Matches[1].Trim().Trim("'", '"')
        }
        elseif ($line -match '^\s*description\s*:\s*(.*)$') {
            $rest = $Matches[1].Trim()
            if ($rest -eq '>-' -or $rest -eq '>' -or $rest -eq '|' -or $rest -eq '|-') {
                # folded scalar -- collect indented continuation
                $buf = @()
                $j = $i + 1
                while ($j -lt $fmLines.Count -and ($fmLines[$j] -match '^\s+\S' -or $fmLines[$j].Trim() -eq '')) {
                    if ($fmLines[$j].Trim().Length -gt 0) {
                        $buf += $fmLines[$j].Trim()
                    }
                    $j++
                }
                $description = ($buf -join ' ').Trim()
                $i = $j - 1
            }
            else {
                $description = $rest.Trim().Trim("'", '"')
            }
        }
        $i++
    }

    if (-not $name) { return $null }
    if (-not $description) { $description = '' }

    return [pscustomobject]@{
        Name        = $name
        Description = $description
    }
}

# Walk canonical skills folder
$skillDirs = Get-ChildItem -Path $canonicalSkillsDir -Directory -Filter 'g-skl-*' | Sort-Object Name
$entries = New-Object System.Collections.ArrayList

foreach ($dir in $skillDirs) {
    $skillFile = Join-Path $dir.FullName 'SKILL.md'
    if (-not (Test-Path $skillFile)) { continue }
    $fm = Get-SkillFrontmatter -Path $skillFile
    if ($null -eq $fm) {
        Write-Warning "Skipping '$($dir.Name)' -- could not parse frontmatter"
        continue
    }
    [void]$entries.Add($fm)
}

# Sort by name for stable output
$entries = $entries | Sort-Object Name

# Build index content
$header = @(
    '# Skill Index -- gald3r-managed skills',
    '',
    '> Auto-generated by `.gald3r_sys/skills/g-skl-setup/scripts/generate_skill_index.ps1`. Do not hand-edit.',
    '> Regenerate after adding/removing/renaming any `g-skl-*` skill.',
    '> Source of truth: `.cursor/skills/g-skl-*/SKILL.md` frontmatter (`name:` + `description:`).',
    '',
    'This index lets agents discover skills without loading the full SKILL.md body.',
    'See `docs/20260507_*_Cursor_SKILL_CHAINING_ARCHITECTURE.md` for the reference-mode',
    'loading contract and the `## Summary` block convention on each individual skill.',
    '',
    '## Index',
    ''
)

$indexLines = New-Object System.Collections.ArrayList
foreach ($e in $entries) {
    [void]$indexLines.Add(('- **{0}**: {1}' -f $e.Name, $e.Description))
}

$content = ($header + $indexLines + '') -join "`n"
# Ensure trailing newline
if (-not $content.EndsWith("`n")) { $content += "`n" }

$changedTargets = @()
$unchangedTargets = @()
$skippedTargets = @()

foreach ($t in $targets) {
    if (-not (Test-Path $t)) {
        $skippedTargets += $t
        continue
    }
    $outPath = Join-Path $t 'SKILL_INDEX.md'
    $existing = ''
    if (Test-Path $outPath) {
        # Read as UTF-8 explicitly so the comparison matches the UTF-8 we write.
        try {
            $existing = [System.IO.File]::ReadAllText($outPath, [System.Text.UTF8Encoding]::new($false))
        } catch {
            $existing = ''
        }
    }
    if ($existing -eq $content) {
        $unchangedTargets += $outPath
    }
    else {
        $changedTargets += $outPath
        if ($Apply) {
            # Use UTF-8 without BOM
            [System.IO.File]::WriteAllText($outPath, $content, [System.Text.UTF8Encoding]::new($false))
        }
    }
}

Write-Host ''
Write-Host '=== Skill Index Generator ==='
Write-Host ('Skills found        : {0}' -f $entries.Count)
Write-Host ('Targets changed     : {0}' -f $changedTargets.Count)
Write-Host ('Targets unchanged   : {0}' -f $unchangedTargets.Count)
Write-Host ('Targets skipped     : {0}' -f $skippedTargets.Count)
if ($changedTargets) {
    Write-Host ''
    Write-Host 'Changed:'
    foreach ($p in $changedTargets) { Write-Host ("  {0}" -f $p) }
}
if ($skippedTargets) {
    Write-Host ''
    Write-Host 'Skipped (no skills folder):'
    foreach ($p in $skippedTargets) { Write-Host ("  {0}" -f $p) }
}
if (-not $Apply -and $changedTargets.Count -gt 0) {
    Write-Host ''
    Write-Host 'DRY RUN -- re-run with -Apply to write changes.'
}
exit 0
