# run_compliance_scan.ps1 — g-skl-compliance PowerShell helper
# Called by @g-compliance-scan and @g-compliance-gate hook.
#
# TODO[TASK-906→TASK-<follow-up>]: Replace stub with full ORT/FOSSA/Snyk/PMD pipeline.
# Current behavior: detect scanner name, print diagnostics, exit 0.
#
# Parameters:
#   -Scanner    Scanner name to use (auto|ort|fossa|snyk|pmd|pmdc|fallback). Default: auto
#   -RepoRoot   Path to repository root. Default: current directory
#   -Strict     If set, WARN exits with code 1 instead of 0

[CmdletBinding()]
param(
    [string]$Scanner = 'auto',
    [string]$RepoRoot = (Get-Location).Path,
    [switch]$Strict
)

$ErrorActionPreference = 'Stop'

# ── Scanner auto-detection ───────────────────────────────────────────────────
$detected = $null

if ($Scanner -ne 'auto') {
    $detected = $Scanner
    Write-Host "g-skl-compliance: using specified scanner: $detected"
} else {
    foreach ($cmd in @('ort', 'fossa', 'snyk', 'pmdc', 'pmd')) {
        if (Get-Command $cmd -ErrorAction SilentlyContinue) {
            $detected = $cmd
            break
        }
    }
    if (-not $detected) {
        $detected = 'fallback'
    }
    Write-Host "g-skl-compliance: auto-detected scanner: $detected"
}

# ── Repo root validation ──────────────────────────────────────────────────────
if (-not (Test-Path $RepoRoot)) {
    Write-Error "g-skl-compliance: repo root not found: $RepoRoot"
    exit 2
}

Write-Host "g-skl-compliance: repo root = $RepoRoot"

# ── Ensure reports dir exists ─────────────────────────────────────────────────
$reportsDir = Join-Path $RepoRoot ".gald3r\reports"
if (-not (Test-Path $reportsDir)) {
    New-Item -ItemType Directory -Path $reportsDir -Force | Out-Null
}

# ── Stub output ──────────────────────────────────────────────────────────────
# TODO[TASK-906→TASK-<follow-up>]: Full scan pipeline implementation.
# When implemented, this stub will be replaced with:
#   - ORT: ort analyze -i $RepoRoot -o $reportsDir/ort_out
#   - FOSSA: fossa analyze && fossa report attribution
#   - Snyk: snyk test --json > $reportsDir/snyk_raw.json
#   - PMD:  pmdc cpd --minimum-tokens 50 --dir $RepoRoot --format xml
#   - Fallback: parse package.json, pyproject.toml, Cargo.toml, go.mod, etc.

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm UTC"
$dateStamp = Get-Date -Format "yyyyMMdd"
$reportPath = Join-Path $reportsDir "compliance_$dateStamp.md"

$stubReport = @"
# Compliance Report — $timestamp

**Scanner**: $detected (stub — full pipeline not yet implemented)
**Repo root**: $RepoRoot
**Verdict**: COMPLIANCE: PASS

## Note

This report was generated by the stub implementation of run_compliance_scan.ps1.
The full scan pipeline is deferred to a follow-up task.

To perform a real compliance scan, install one of the supported scanners:
- ORT: https://github.com/oss-review-toolkit/ort/releases
- FOSSA: https://github.com/fossas/fossa-cli
- Snyk: npm install -g snyk && snyk auth

## Summary Table

| Package | Version | Declared License | Risk |
|---------|---------|-----------------|------|
| (stub — no packages scanned) | — | — | — |

## Verdict

COMPLIANCE: PASS (stub — no real scan performed)
"@

$stubReport | Set-Content -Path $reportPath -Encoding UTF8
Write-Host "g-skl-compliance: report written to $reportPath"
Write-Host "g-skl-compliance: COMPLIANCE: PASS (stub)"

exit 0
